In [1]:
import numpy as np

In [2]:
arr = np.array([1 ,2, 3])
arr

array([1, 2, 3])

In [5]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [10]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
np.random.rand(3, 2)

array([[0.05366734, 0.51219171],
       [0.93768667, 0.75514425],
       [0.0646438 , 0.22560413]])

In [12]:
np.random.randn(3, 2)

array([[ 0.10019783, -0.29177823],
       [ 0.78171517,  1.89557241],
       [ 0.35287447,  0.977916  ]])

In [16]:
arr = np.array(([1, 2, 3], [4, 5, 6]))
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
print(arr.shape)

(2, 3)


In [18]:
print(arr.ndim)

2


In [19]:
print(arr.size)

6


In [20]:
print(arr.dtype)

int64


In [21]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [22]:
a + b

array([5, 7, 9])

In [23]:
a * b

array([ 4, 10, 18])

In [24]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [25]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [26]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [27]:
A @ B

array([[19, 22],
       [43, 50]])

In [29]:
arr = np. array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [30]:
arr.sum( )

np.int64(10)

In [31]:
arr.mean( )

np.float64(2.5)

In [32]:
arr.max( )

np.int64(4)

In [33]:
arr.min( )

np.int64(1)

In [34]:
arr.std( )

np.float64(1.118033988749895)

In [35]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [36]:
arr[0]

np.int64(1)

In [37]:
arr[1:4]

array([2, 3, 4])

In [38]:
arr[::2]

array([1, 3, 5])

In [39]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
arr[0, 1]

np.int64(2)

In [41]:
arr[:, 1]

array([2, 5])

In [42]:
arr[1, :2]

array([4, 5])

In [43]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [47]:
mask = arr > 3
mask

array([False, False, False,  True,  True])

In [48]:
arr[mask]

array([4, 5])

In [50]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [51]:
arr.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [52]:
a = np.array([1, 2])
b = np.array([3,4])

In [54]:
np.concatenate((a, b))

array([1, 2, 3, 4])

In [55]:
np.vstack((a, b))

array([[1, 2],
       [3, 4]])

In [56]:
np.hstack((a, b))

array([1, 2, 3, 4])

In [58]:
a = np.array([1, 2, 3])
a + 5 # [6, 7, 8]

array([6, 7, 8])

In [59]:
np.save('array.npy',arr)

In [60]:
loaded_arr = np.load('array.npy')
loaded_arr

array([0, 1, 2, 3, 4, 5])